[project]
name = "titelive"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "factories",
    "aiohttp>=3.9",
    "gcloud-aio-storage>=9.6",
    "google-cloud-bigquery>=3.0",
    "google-cloud-storage>=2.16",
    "pandas>=2.2",
    "pandas-gbq>=0.19",
    "pyarrow>=21.0",
    "tqdm>=4.67",
    "typer>=0.12",
]

[tool.uv.sources]
factories = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff]
target-version = "py312"
lint.select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 100

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-type-checking]
strict = true
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
