[project]
name = "allocine"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-bigquery>=3.0.0",
    "google-cloud-secret-manager>=2.24.0",
    "google-cloud-storage>=2.16.0",
    "httpx>=0.27.0",
    "pyarrow>=21.0.0",
    "typer>=0.12.3",
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
